# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'kwikpic.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *

import logo_rc

class Ui_Kwikpic(object):
    def setupUi(self, Kwikpic):
        if not Kwikpic.objectName():
            Kwikpic.setObjectName(u"Kwikpic")
        Kwikpic.resize(800, 600)
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Kwikpic.sizePolicy().hasHeightForWidth())
        Kwikpic.setSizePolicy(sizePolicy)
        Kwikpic.setMinimumSize(QSize(800, 600))
        Kwikpic.setMaximumSize(QSize(800, 600))
        icon = QIcon()
        icon.addFile(u"../../OneDrive/Documents/logo, favicon/Group 2015@LDPI.png", QSize(), QIcon.Normal, QIcon.Off)
        Kwikpic.setWindowIcon(icon)
        Kwikpic.setAutoFillBackground(False)
        self.centralwidget = QWidget(Kwikpic)
        self.centralwidget.setObjectName(u"centralwidget")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(0, 0, 791, 591))
        sizePolicy1 = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy1)
        font = QFont()
        font.setBold(False)
        font.setWeight(50)
        font.setStyleStrategy(QFont.PreferDefault)
        self.tabWidget.setFont(font)
#if QT_CONFIG(accessibility)
        self.tabWidget.setAccessibleName(u"")
#endif // QT_CONFIG(accessibility)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.watermark = QWidget()
        self.watermark.setObjectName(u"watermark")
        self.watermark_src = QLineEdit(self.watermark)
        self.watermark_src.setObjectName(u"watermark_src")
        self.watermark_src.setGeometry(QRect(160, 150, 381, 21))
        font1 = QFont()
        font1.setBold(False)
        font1.setWeight(50)
        self.watermark_src.setFont(font1)
        self.watermark_position = QComboBox(self.watermark)
        self.watermark_position.setObjectName(u"watermark_position")
        self.watermark_position.setGeometry(QRect(160, 230, 121, 21))
        self.watermark_position.setEditable(False)
        self.watermark_size = QLineEdit(self.watermark)
        self.watermark_size.setObjectName(u"watermark_size")
        self.watermark_size.setGeometry(QRect(530, 280, 71, 21))
        sizePolicy2 = QSizePolicy(QSizePolicy.Maximum, QSizePolicy.Fixed)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.watermark_size.sizePolicy().hasHeightForWidth())
        self.watermark_size.setSizePolicy(sizePolicy2)
        self.watermark_size.setMaximumSize(QSize(16777215, 16777215))
        font2 = QFont()
        font2.setPointSize(13)
        self.watermark_size.setFont(font2)
        self.label_9 = QLabel(self.watermark)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(160, 129, 121, 21))
        font3 = QFont()
        font3.setFamily(u"Montserrat")
        font3.setPointSize(10)
        font3.setBold(True)
        font3.setWeight(75)
        font3.setKerning(True)
        font3.setStyleStrategy(QFont.PreferAntialias)
        self.label_9.setFont(font3)
        self.watermark_submit = QPushButton(self.watermark)
        self.watermark_submit.setObjectName(u"watermark_submit")
        self.watermark_submit.setGeometry(QRect(320, 360, 131, 21))
        self.label_14 = QLabel(self.watermark)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(560, 260, 51, 21))
        font4 = QFont()
        font4.setPointSize(8)
        self.label_14.setFont(font4)
        self.label_12 = QLabel(self.watermark)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(220, 20, 301, 131))
        self.label_12.setPixmap(QPixmap(u"../../../Downloads/Primary_Logo.png"))
        self.watermark_browse_src = QPushButton(self.watermark)
        self.watermark_browse_src.setObjectName(u"watermark_browse_src")
        self.watermark_browse_src.setGeometry(QRect(550, 150, 71, 21))
        self.watermark_type_combo = QComboBox(self.watermark)
        self.watermark_type_combo.setObjectName(u"watermark_type_combo")
        self.watermark_type_combo.setGeometry(QRect(310, 230, 81, 22))
        self.watermark_cropped_src_or_text = QLineEdit(self.watermark)
        self.watermark_cropped_src_or_text.setObjectName(u"watermark_cropped_src_or_text")
        self.watermark_cropped_src_or_text.setGeometry(QRect(160, 280, 261, 21))
        self.watermark_cropped_src_or_text.setFont(font1)
        self.watermark_cropped_src_browse = QPushButton(self.watermark)
        self.watermark_cropped_src_browse.setObjectName(u"watermark_cropped_src_browse")
        self.watermark_cropped_src_browse.setGeometry(QRect(430, 280, 61, 21))
        self.label_23 = QLabel(self.watermark)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(320, 190, 231, 21))
        self.label_23.setFont(font3)
        self.label_24 = QLabel(self.watermark)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(530, 260, 31, 21))
        self.label_24.setFont(font3)
        self.label_25 = QLabel(self.watermark)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(160, 210, 51, 21))
        self.label_25.setFont(font3)
        self.label_26 = QLabel(self.watermark)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(310, 210, 51, 21))
        self.label_26.setFont(font3)
        self.watermark_type_label = QLabel(self.watermark)
        self.watermark_type_label.setObjectName(u"watermark_type_label")
        self.watermark_type_label.setGeometry(QRect(160, 260, 51, 21))
        self.watermark_type_label.setFont(font3)
        self.label_28 = QLabel(self.watermark)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(160, 320, 231, 21))
        self.label_28.setFont(font3)
        self.watermark_optimize_checkbox = QCheckBox(self.watermark)
        self.watermark_optimize_checkbox.setObjectName(u"watermark_optimize_checkbox")
        self.watermark_optimize_checkbox.setGeometry(QRect(400, 320, 21, 21))
        self.watermark_progress = QLabel(self.watermark)
        self.watermark_progress.setObjectName(u"watermark_progress")
        self.watermark_progress.setGeometry(QRect(160, 400, 441, 121))
        self.watermark_progress.setFont(font3)
        self.tabWidget.addTab(self.watermark, "")
        self.optimize = QWidget()
        self.optimize.setObjectName(u"optimize")
        self.optimize_submit = QPushButton(self.optimize)
        self.optimize_submit.setObjectName(u"optimize_submit")
        self.optimize_submit.setGeometry(QRect(330, 270, 81, 21))
        self.optimize_src = QLineEdit(self.optimize)
        self.optimize_src.setObjectName(u"optimize_src")
        self.optimize_src.setGeometry(QRect(170, 190, 401, 21))
        self.optimize_src.setFont(font1)
        self.optimize_destination = QLineEdit(self.optimize)
        self.optimize_destination.setObjectName(u"optimize_destination")
        self.optimize_destination.setGeometry(QRect(170, 240, 401, 21))
        self.optimize_destination.setFont(font1)
        self.label_16 = QLabel(self.optimize)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(240, 50, 301, 131))
        self.label_16.setPixmap(QPixmap(u"../../../Downloads/Primary_Logo.png"))
        self.optimize_browse_src = QPushButton(self.optimize)
        self.optimize_browse_src.setObjectName(u"optimize_browse_src")
        self.optimize_browse_src.setGeometry(QRect(580, 190, 71, 21))
        self.optimize_browse_destination = QPushButton(self.optimize)
        self.optimize_browse_destination.setObjectName(u"optimize_browse_destination")
        self.optimize_browse_destination.setGeometry(QRect(580, 240, 71, 21))
        self.label_10 = QLabel(self.optimize)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(170, 170, 91, 21))
        self.label_10.setFont(font3)
        self.label_11 = QLabel(self.optimize)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(170, 220, 121, 21))
        self.label_11.setFont(font3)
        self.optimize_progress = QLabel(self.optimize)
        self.optimize_progress.setObjectName(u"optimize_progress")
        self.optimize_progress.setGeometry(QRect(170, 330, 481, 141))
        self.optimize_progress.setFont(font3)
        self.tabWidget.addTab(self.optimize, "")
        self.rename = QWidget()
        self.rename.setObjectName(u"rename")
        self.rename_src = QLineEdit(self.rename)
        self.rename_src.setObjectName(u"rename_src")
        self.rename_src.setGeometry(QRect(210, 220, 361, 21))
        self.rename_src.setFont(font1)
        self.rename_submit = QPushButton(self.rename)
        self.rename_submit.setObjectName(u"rename_submit")
        self.rename_submit.setGeometry(QRect(330, 260, 111, 21))
        self.label_15 = QLabel(self.rename)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(260, 60, 301, 131))
        self.label_15.setPixmap(QPixmap(u"../../../Downloads/Primary_Logo.png"))
        self.rename_browse_src = QPushButton(self.rename)
        self.rename_browse_src.setObjectName(u"rename_browse_src")
        self.rename_browse_src.setGeometry(QRect(580, 220, 71, 21))
        self.label_20 = QLabel(self.rename)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(210, 200, 91, 21))
        self.label_20.setFont(font3)
        self.rename_progress = QLabel(self.rename)
        self.rename_progress.setObjectName(u"rename_progress")
        self.rename_progress.setGeometry(QRect(210, 330, 441, 141))
        self.rename_progress.setFont(font3)
        self.tabWidget.addTab(self.rename, "")
        self.copy = QWidget()
        self.copy.setObjectName(u"copy")
        self.copy_submit = QPushButton(self.copy)
        self.copy_submit.setObjectName(u"copy_submit")
        self.copy_submit.setGeometry(QRect(330, 320, 81, 21))
        self.copy_src_textFile = QLineEdit(self.copy)
        self.copy_src_textFile.setObjectName(u"copy_src_textFile")
        self.copy_src_textFile.setGeometry(QRect(170, 220, 391, 21))
        self.label_17 = QLabel(self.copy)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(230, 60, 301, 131))
        self.label_17.setPixmap(QPixmap(u"../../../Downloads/Primary_Logo.png"))
        self.copy_browse_src_textFile = QPushButton(self.copy)
        self.copy_browse_src_textFile.setObjectName(u"copy_browse_src_textFile")
        self.copy_browse_src_textFile.setGeometry(QRect(570, 220, 71, 21))
        self.copy_src_folder = QLineEdit(self.copy)
        self.copy_src_folder.setObjectName(u"copy_src_folder")
        self.copy_src_folder.setGeometry(QRect(170, 280, 391, 21))
        self.copy_browse_src_folder = QPushButton(self.copy)
        self.copy_browse_src_folder.setObjectName(u"copy_browse_src_folder")
        self.copy_browse_src_folder.setGeometry(QRect(570, 280, 71, 21))
        self.label_29 = QLabel(self.copy)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(170, 200, 91, 21))
        self.label_29.setFont(font3)
        self.label_30 = QLabel(self.copy)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(170, 260, 121, 21))
        self.label_30.setFont(font3)
        self.copy_progress = QLabel(self.copy)
        self.copy_progress.setObjectName(u"copy_progress")
        self.copy_progress.setGeometry(QRect(170, 360, 471, 131))
        self.copy_progress.setFont(font3)
        self.tabWidget.addTab(self.copy, "")
        Kwikpic.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(Kwikpic)
        self.statusbar.setObjectName(u"statusbar")
        Kwikpic.setStatusBar(self.statusbar)

        self.retranslateUi(Kwikpic)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(Kwikpic)
    # setupUi

    def retranslateUi(self, Kwikpic):
        Kwikpic.setWindowTitle(QCoreApplication.translate("Kwikpic", u"Kwikpic", None))
        self.label_9.setText(QCoreApplication.translate("Kwikpic", u"Source Folder", None))
        self.watermark_submit.setText(QCoreApplication.translate("Kwikpic", u"Add Watermark", None))
        self.label_14.setText(QCoreApplication.translate("Kwikpic", u"(in pts)", None))
        self.label_12.setText("")
        self.watermark_browse_src.setText(QCoreApplication.translate("Kwikpic", u"Browse", None))
        self.watermark_cropped_src_browse.setText(QCoreApplication.translate("Kwikpic", u"Browse", None))
        self.label_23.setText(QCoreApplication.translate("Kwikpic", u"<html><head/><body><p><span style=\" font-size:11pt; color:#0f80ff;\">Watermark Details</span></p></body></html>", None))
        self.label_24.setText(QCoreApplication.translate("Kwikpic", u"Size", None))
        self.label_25.setText(QCoreApplication.translate("Kwikpic", u"Position", None))
        self.label_26.setText(QCoreApplication.translate("Kwikpic", u"Type", None))
        self.watermark_type_label.setText(QCoreApplication.translate("Kwikpic", u"Image", None))
        self.label_28.setText(QCoreApplication.translate("Kwikpic", u"Do you want to optimze the images as well?", None))
        self.watermark_optimize_checkbox.setText("")
        self.watermark_progress.setText(QCoreApplication.translate("Kwikpic", u"Click \"Add Watermark\" to continue...", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.watermark), QCoreApplication.translate("Kwikpic", u"Watermark", None))
        self.optimize_submit.setText(QCoreApplication.translate("Kwikpic", u"Optimize", None))
        self.optimize_src.setText("")
        self.label_16.setText("")
        self.optimize_browse_src.setText(QCoreApplication.translate("Kwikpic", u"Browse", None))
        self.optimize_browse_destination.setText(QCoreApplication.translate("Kwikpic", u"Browse", None))
        self.label_10.setText(QCoreApplication.translate("Kwikpic", u"Source Folder", None))
        self.label_11.setText(QCoreApplication.translate("Kwikpic", u"Destination Folder", None))
        self.optimize_progress.setText(QCoreApplication.translate("Kwikpic", u"Click \"Optimize\" to continue...", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.optimize), QCoreApplication.translate("Kwikpic", u"Optimize", None))
        self.rename_submit.setText(QCoreApplication.translate("Kwikpic", u"Rename Files", None))
        self.label_15.setText("")
        self.rename_browse_src.setText(QCoreApplication.translate("Kwikpic", u"Browse", None))
        self.label_20.setText(QCoreApplication.translate("Kwikpic", u"Source Folder", None))
        self.rename_progress.setText(QCoreApplication.translate("Kwikpic", u"Click \"Rename Files\" to continue", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.rename), QCoreApplication.translate("Kwikpic", u"Rename", None))
        self.copy_submit.setText(QCoreApplication.translate("Kwikpic", u"Copy", None))
        self.label_17.setText("")
        self.copy_browse_src_textFile.setText(QCoreApplication.translate("Kwikpic", u"Browse", None))
        self.copy_browse_src_folder.setText(QCoreApplication.translate("Kwikpic", u"Browse", None))
        self.label_29.setText(QCoreApplication.translate("Kwikpic", u"Source Folder", None))
        self.label_30.setText(QCoreApplication.translate("Kwikpic", u"Destination Folder", None))
        self.copy_progress.setText(QCoreApplication.translate("Kwikpic", u"Click on \"Copy\" to continue...", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.copy), QCoreApplication.translate("Kwikpic", u"Copy", None))
    # retranslateUi

